<!--
The Ryuu Technology License

Copyright 2014 Ryuu Technology by 
KatsuoRyuu <anders-github@drake-development.org>.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
Ryuu Technology shall be visible and readable to anyone using the software 
and shall be written in one of the following ways: 竜技術, Ryuu Technology 
or by using the company logo.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->
<?php
$title = 'Posts';
$this->headTitle($title,$this->placeholder('titleType')->set('PREPEND'));
//$this->HeadlineNote()->add($title,'Blog posting administration.');
    
?>
<p><a href="<?php echo $this->url('contact/company', array('action'=>'add'));?>">Add Company</a></p>
<table class="table table-bordered table-hover">
    <tr>
        <th>Post</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($companies as $company) : ?>
	    <tr>
	        <td>
               <?php echo $this->escapeHtml($company->__get('name'));?>:
            </td>
	        <td>
	            <a href="<?php echo $this->url('contact/company', array('action' => 'edit', 'id'=>$company->__get('id'))); ?>">Edit</a>
	        </td>
	        <td>
	            <a href="<?php echo $this->url('contact/company', array('action' => 'delete', 'id'=>$company->__get('id'))); ?>" onclick="return confirm('Are you sure?')">Delete</a>
	        </td>
	        <td>
	            <a href="<?php echo $this->url('contact/company', array('action' => 'addContact', 'id'=>$company->__get('id'))); ?>" >Add contact info</a>
	        </td>
	    </tr>
        <?php foreach($company->getContacts() as $contact) : ?>
            <tr>
                <td>
                    <dd><?php echo $this->escapeHtml($contact->__get('area'));?></dd>
                </td>
                <!--
                <td>
                    <a href="<?php echo $this->url('contact/company', array('action' => 'edit', 'id'=>$company->__get('id'))); ?>">Edit</a>
                </td>
                -->
                <td>
                    <a href="<?php echo $this->url('contact/company', array('action' => 'deleteContact', 'id'=>$company->__get('id'), 'id2'=>$contact->__get('id'))); ?>" onclick="return confirm('Are you sure?')">Delete</a>
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
</table>