<?php
/**
 * @encoding UTF-8
 * @note *
 * @todo *
 * @package PackageName
 * @author Anders Blenstrup-Pedersen - KatsuoRyuu <anders-github@drake-development.org>
 * @license 
 * The Ryuu Technology License
 *
 * Copyright 2014 Ryuu Technology by 
 * KatsuoRyuu <anders-github@drake-development.org>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * Ryuu Technology shall be visible and readable to anyone using the software 
 * and shall be written in one of the following ways: 竜技術, Ryuu Technology 
 * or by using the company logo.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *

 * @version 20140507 
 * @link https://github.com/KatsuoRyuu/
 */
?>


<?php

$this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?sensor=false');

?>

<?php if(0): ?><style type="text/css" media="screen"><?php endif; ?>
<?php $this->headStyle()->captureStart(); ?>
div.contact{
    font-family: Calibri,Verdana,Arial,Helvetica,sans-serif;
}

#map_canvas {
    float:left;
    width: 300px;
    height: 300px;
    margin-right:10px;
}

<?php $this->headStyle()->captureEnd() ?>   
<?php if (0) : ?></style><?php endif; ?>

<?php if(0): ?><script><?php endif; ?>
<?php $this->headScript()->captureStart() ?>
    

function initialize() {

    var geocoder = new google.maps.Geocoder();
    var address = '<?= $company->__get('address') ?> <?= $company->__get('zip') ?> <?= $company->__get('city') ?>';

    geocoder.geocode({
        address: address
    }, 
    function(results, status) {
        if(status == google.maps.GeocoderStatus.OK) {    
            var mapOptions = { 
                mapTypeId: google.maps.MapTypeId.TERRAIN,
                zoom: 14,
                center: results[0].geometry.location,
                mapTypeControlOptions: { 
                    style: google.maps.MapTypeControlStyle.DEFAULT,
                    position: google.maps.ControlPosition.TOP_RIGHT
                }, 
                zoomControl: true,
                zoomControlOptions: {
                    style: google.maps.ZoomControlStyle.DEFAULT,
                    position: google.maps.ControlPosition.TOP_LEFT
                },
                panControl: true,
                panControlOptions: {
                    position: google.maps.ControlPosition.TOP_LEFT
                },
                scaleControl: true,
                streetViewControl: true,
                streetViewControlOptions: {
                    position: google.maps.ControlPosition.TOP_LEFT
                },
                scrollwheel: false
            }
            var map = new google.maps.Map(document.getElementById("contact-map"), mapOptions);
            new google.maps.Marker({
                position:results[0].geometry.location,
                map: map
            });  
        }
    });  
}
google.maps.event.addDomListener(window, 'load', initialize);

<?php $this->headScript()->captureEnd() ?>
<?php if (0) : ?></script><?php endif; ?>

<?php
$companyForm = $this->companyForm;
$companyForm->setAttribute('action', $this->url('contact/message', array('action'=>'add')));

$companyForm->add(array(
    'name'=> 'submit',
    'type'=> 'Zend\Form\Element\Submit',
    'attributes'=> array(
        'value'=> 'Submit',
        'required'=> 'false',
        ),
    )
);


?>


<section class="clearfix" id="Contacts">
        <header class="item-header-wrap">
            <div class="item-header screen-large">
                <div class="logo_content" >
                    <h2 class="logo">Kontakt</h2>
                </div>

                <div class="title-shadow"></div>
            </div>
        </header>
        

        <div id="contact-map" style="z-index: -100; margin-top:-30px; height:800px;"></div>
        <div class="page-content screen-large" style="margin-top:-700px;">
        
            <div style="background-color:rgba(255,255,255,0.8); width: 220px; padding:10px; border-radius: 5px;">      
                <?= $company->__get('name') ?><br />
                <?= $company->__get('address') ?><br />
                <?= $company->__get('zip') ?> <?= $company->__get('city') ?><br />
                <?= $company->__get('country') ?><br /><br />
                <?= $this->translate('Phone').': '.$company->__get('phone') ?><br /><br />

                <?php
                    $companyForm->prepare();
                    echo $this->ztbForm($companyForm);
                ?>
            </div>
        </div>

    </section>
<!-- Tab panes -->

