<?php
/**
 * @encoding UTF-8
 * @note *
 * @todo *
 * @package PackageName
 * @author Anders Blenstrup-Pedersen - KatsuoRyuu <anders-github@drake-development.org>
 * @license *
 * The Ryuu Technology License
 *
 * Copyright 2014 Ryuu Technology by 
 * KatsuoRyuu <anders-github@drake-development.org>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * Ryuu Technology shall be visible and readable to anyone using the software 
 * and shall be written in one of the following ways: 竜技術, Ryuu Technology 
 * or by using the company logo.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *

 * @version 20140507 
 * @link https://github.com/KatsuoRyuu/
 */
?>


<?php

$this->ScriptRepo($this->serverUrl(true))->needScript('angular-js','1.3.0','JS')
                ->needScript('bootstrap','3.1.1','JS')
                ->needScript('bootstrap-theme','3.1.1','CSS');
$this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?sensor=false');

?>

<?php if(0): ?><style type="text/css" media="screen"><?php endif; ?>
<?php $this->headStyle()->captureStart(); ?>
div.contact{
    font-family: Calibri,Verdana,Arial,Helvetica,sans-serif;
}

#map_canvas {
    float:left;
    width: 300px;
    height: 300px;
    margin-right:10px;
}

<?php $this->headStyle()->captureEnd() ?>   
<?php if (0) : ?></style><?php endif; ?>

<?php if(0): ?><script><?php endif; ?>
<?php $this->headScript()->captureStart() ?>
    
$('#myTab a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})
function initialize() {

    var geocoder = new google.maps.Geocoder();
    var address = '<?= $company->__get('address') ?> <?= $company->__get('zip') ?> <?= $company->__get('city') ?>';

    geocoder.geocode({
        address: address
    }, 
    function(results, status) {
        if(status == google.maps.GeocoderStatus.OK) {    
            var mapOptions = { 
            mapTypeId: google.maps.MapTypeId.TERRAIN,
            zoom: 14,
            center: results[0].geometry.location
            }
            var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
            new google.maps.Marker({
                position:results[0].geometry.location,
                map: map
            });  
        }
    });  
}
google.maps.event.addDomListener(window, 'load', initialize);

<?php $this->headScript()->captureEnd() ?>
<?php if (0) : ?></script><?php endif; ?>

<?php
$companyForm = $this->companyForm;
$companyForm->setAttribute('action', $this->url('contact'));

$companyForm->add(array(
    'name'=> 'submit',
    'type'=> 'Zend\Form\Element\Submit',
    'attributes'=> array(
        'value'=> 'Submit',
        'required'=> 'false',
        ),
    )
);


?>

    <?php foreach ($staffs as $staff): ?>      
            <h2><?= $staff->__get('name') ?> <?= $staff->__get('lastname') ?></h2>
            <?= $staff->__get('country') ?><br /><br />
            <?= $this->translate('Phone').': '.$staff->__get('phone') ?><br /><br />
            
            <?php
                
                $contactsArray = $staff->getContacts()->toArray();
                $mails = array();
                foreach($contactsArray as $contact){
                    $mails[$contact->__get('id')] = $contact->__get('area');
                }
                $companyForm->get('about')->setValueOptions($mails);
                $companyForm->prepare();
                echo $this->ztbForm($companyForm);
            ?>
    <?php endforeach; ?>
